apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  # replicas: 2
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_alpine
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftp
        - containerPort: 21
          name: ftps
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
        - containerPort: 21005
        - containerPort: 21006
        - containerPort: 21007
        - containerPort: 21008
