apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  # replicas: 2
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_alpine
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftp
        - containerPort: 21
          name: ftps
        - containerPort: 21009
          name: pasv-min
        - containerPort: 21010
          name: pasv-mid
        - containerPort: 21011
          name: pasv-max
