apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: sql_port
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
  # loadBalancerIP: 172.17.0.X
